version: 1.0.{build}
build_script:
- ps: .\build.ps1

artifacts:    
  - path: .\build\*.nupkg

skip_tags: true

deploy:
  provider: NuGet
  api_key:
    secure: +pULnhe+Gbb9ZNXznGYRKKRXwWsXMU9Q21Ya3YB5s4cdKzUT7+tQ9QnOgitOk/oW
  skip_symbols : true  
  on:
    branch: master

environment:
  access_token:
    secure: Ezm9yOuGI+UAT4+HvumnvKyIh15SWeNS4PvrzbXnQWIjSCJUMwcl2/zaXS69MrqZ

on_success:
  - ps: ./appveyor.onsuccess.ps1
    